<?php
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatch;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Cmf\Component\Routing\RouteObjectInterface;
use Symfony\Component\Routing\Route;
use Drupal\dea_request\Routing\RequestableRouteEnhancer;

/**
 * Implements hook_entity_operation().
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function dea_request_entity_operation(EntityInterface $entity) {
  $operations = [];
  if ($entity->getEntityTypeId() == 'dea_request') {
    $operations['accept'] = [
      'title' => t('Accept'),
      'url' => $entity->urlInfo('accept'),
    ];
    $operations['deny'] = [
      'title' => t('Deny'),
      'url' => $entity->urlInfo('deny'),
    ];
  }
  return $operations;
}

/**
 * Implements hook_link_alter().
 */
function dea_request_link_alter(&$variables) {
  $variables['options']['attributes'] += \Drupal::getContainer()
    ->get('dea_request.link_marker')
    ->attributes($variables['url']);
  $variables['options']['#attached'] = [
    'library' => [
      'dea_request/access_check',
      'drupal/ajax'
    ],
  ];
}

/**
 * Implements hook_page_attachments_alter().
 */
function dea_request_page_attachments_alter(array &$attachments) {
  $attachments['#attached']['library'][] = 'dea_request/access_check';
}
